### ISSUE TITLE
Logrotation config files might be writable by group

### ISSUE THREAD

**Issue by miklschmidt** [mainsail-crew/MainsailOS#170] opened 2022-11-12 14:53 UTC
### What happened

So i don't know if this applies to you guys, but the logrotation configs supplied by the mainsail module ended up being 664 instead of 644 in the image, so logrotate would ignore those and the logs would just pile up.

### What did you expect to happen

Logrotation.d files should be chmodded to 644 (i'm doing this in the `start_chroot_script` now).

### How to reproduce
`sudo /usr/sbin/logrotate /etc/logrotate.conf`
`ls -la /etc/logrotation.d`

### Additional information

This might very well be a RatOS only issue, but i just wanted to keep you guys posted in case it carried over from MainsailOS. Feel free to close!

**Comment by miklschmidt** [comment] 2022-11-12 14:55
See https://github.com/Rat-OS/RatOS/issues/39

**Comment by KwadFan** [comment] 2022-11-16 17:37
Hey @miklschmidt ,

Will do some tests at the weekend, may an issue due who Custompios copies files.
In the source the files are as expected 0644 ... :man_shrugging:

**Comment by KwadFan** [comment] 2022-11-23 08:03
Hey @miklschmidt ,

Made some tests. Short tests but they work. @zellneralex is doing a Longterm Test right now, will report results.
![Bildschirmfoto_2022-11-23_08-59-09](https://user-images.githubusercontent.com/43513802/203497057-8322b9b6-38f2-4376-9e18-fc9682f565ea.png)
![Bildschirmfoto_2022-11-23_08-57-47](https://user-images.githubusercontent.com/43513802/203497069-079d11d5-c30f-4339-b72a-ee599251087d.png)

Regards Kwad

**Comment by miklschmidt** [comment] 2022-11-23 09:15
Well the permissions look fine, so the problem i had shouldn't be present at least :)

**Comment by KwadFan** [comment] 2022-12-26 12:18
@miklschmidt 

Could you reproduce that with 1.0.0 ?

**Comment by KwadFan** [comment] 2023-03-12 10:48
Closing issue due no further interaction and not reproducable since new release.

**Closed by KwadFan** 2023-03-12 10:48 UTC
Labels: bug

**Comment by miklschmidt** [comment] 2023-03-12 14:12
> Closing issue due no further interaction and not reproducable since new release.

Sorry i forgot to get back to you on this, everything looks good on my end, so closing is appropriate 👍
